# Generated by Django 4.0.2 on 2022-02-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseLevel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('device_timestamp', models.DateTimeField()),
                (
                    'glucose_value_history',
                    models.IntegerField(
                        null=True, verbose_name='Glucose value history mg/dL'
                    ),
                ),
                (
                    'glucose_scan',
                    models.IntegerField(
                        null=True, verbose_name='Glucose scan mg/dL'
                    ),
                ),
                (
                    'rapid_acting_insulin',
                    models.CharField(
                        max_length=128,
                        null=True,
                        verbose_name='Non-numeric rapid-acting insulin',
                    ),
                ),
                (
                    'rapid_acting_insulin_units',
                    models.IntegerField(
                        null=True, verbose_name='Rapid-Acting Insulin (Units)'
                    ),
                ),
                (
                    'nutritional_data',
                    models.CharField(
                        max_length=128,
                        null=True,
                        verbose_name='Non-numeric nutritional data',
                    ),
                ),
                (
                    'carbohydrates_grams',
                    models.IntegerField(
                        null=True, verbose_name='Carbohydrates (grams)'
                    ),
                ),
                (
                    'carbohydrates_servings',
                    models.IntegerField(
                        null=True, verbose_name='Carbohydrates (servings)'
                    ),
                ),
                (
                    'depot_insulin',
                    models.CharField(
                        max_length=128,
                        null=True,
                        verbose_name='Non-numeric depot insulin',
                    ),
                ),
                (
                    'depot_insulin_units',
                    models.IntegerField(
                        null=True, verbose_name='Depot insulin (units)'
                    ),
                ),
                ('notes', models.TextField(null=True)),
                (
                    'glucose_test_strips',
                    models.IntegerField(
                        null=True, verbose_name='Glucose test strips mg/dL'
                    ),
                ),
                (
                    'ketone',
                    models.IntegerField(
                        null=True, verbose_name='Ketone mmol/L'
                    ),
                ),
                (
                    'meal_insulin',
                    models.IntegerField(
                        null=True, verbose_name='Meal Insulin (units)'
                    ),
                ),
                (
                    'correction_insulin',
                    models.IntegerField(
                        null=True, verbose_name='Correction insulin (units)'
                    ),
                ),
                (
                    'user_insulin_changes',
                    models.IntegerField(
                        null=True, verbose_name='User Insulin Change (Units)'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='levels.user',
                    ),
                ),
                (
                    'device',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='devices.device',
                        verbose_name='Device',
                    ),
                ),
                (
                    'recording_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='devices.recordingtype',
                        verbose_name='Revording type',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='glucoselevel',
            constraint=models.UniqueConstraint(
                fields=('created_by', 'device_timestamp'),
                name='unique_item_for_user',
            ),
        ),
    ]
