# Generated by Django 4.0.2 on 2022-02-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glucoselevel',
            options={'ordering': ['device_timestamp']},
        ),
    ]
